-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 15, 2015 at 03:22 AM

-- --------------------------------------------------------

--
-- Table structure for table `rating_mpaa`
--

CREATE TABLE IF NOT EXISTS `rating_mpaa` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `label` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci,
  `description_short` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `short_sweet` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `label` (`label`),
  UNIQUE KEY `name` (`name`),
  KEY `description_short` (`description_short`),
  KEY `short_sweet` (`short_sweet`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;

--
-- Dumping data for table `rating_mpaa`
--

INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'G', 'General Audiences', 'This is a film which contains nothing in theme, language, nudity and sex, violence, etc. which would, in the view of the Rating Board, be offensive to parents whose younger children view the film. The G rating is not a "certificate of approval," nor does it signify a children''s film. Some snippets of language may go beyond polite conversation but they are common everyday expressions. No stronger words are present in G-rated films. The violence is at a minimum. Nudity and sex scenes are not present; nor is there any drug use content.', 'General Audiences. All Ages Admitted.', 'Nothing that would offend parents for viewing by children.');
INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'PG', 'Parental Guidance Suggested', 'This is a film which clearly needs to be examined or inquired into by parents before they let their children under 10 attend. The label PG plainly states that parents may consider some material unsuitable for their children under 10, but the parent must make the decision. Parents are warned against sending their children, unseen and without inquiry, to PG-rated movies. The theme of a PG-rated film may itself call for parental guidance. There may be some profanity in these films. There may be some violence or brief nudity. But these elements are not deemed so intense as to require that parents be strongly cautioned beyond the suggestion of parental guidance. There is no drug use content in a PG-rated film. A child could find the PG rated film sad and scary, a PG rating however should not unsettle a child age 10 or older. The PG rating, suggesting parental guidance, is thus an alert for examination of a film by parents before deciding on its viewing by their children. Obviously such a line is difficult to draw. In our pluralistic society it is not easy to make judgments without incurring some disagreement. So long as parents know they must exercise parental responsibility, the rating serves as a meaningful guide and as a warning.', 'Parental Guidance suggested. Some material may not be suitable for children.', 'Parents urged to give "parental guidance". May contain some material parents might not like for their young children.');
INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'PG-13', 'Parents Strongly Cautioned', 'PG-13 is a sterner warning to parents to determine for themselves the attendance in particular of their younger children as they might consider some material not suited for them. Parents, by the rating, are alerted to be very careful about the attendance of their under-teenage children. A PG-13 film is one which, in the view of the Rating Board, leaps beyond the boundaries of the PG rating in theme, violence, nudity, sensuality, language, or other contents, but does not quite fit within the restricted R category. Any drug use content will initially require at least a PG-13 rating. In effect, the PG-13 cautions parents with more stringency than usual to give special attention to this film before they allow their 12-year olds and younger to attend. If nudity is sexually oriented, the film will generally not be found in the PG-13 category. If violence is too rough or persistent, the film goes into the R (restricted) rating. A film''s single use of one of the harsher sexually-derived words, though only as an expletive, shall initially require the Rating Board to issue that film at least a PG-13 rating. More than one such expletive must lead the Rating Board to issue a film an R rating, as must even one of these words used in a sexual context. These films can be rated less severely, however, if by a special vote, the Rating Board feels that a lesser rating would more responsibly reflect the opinion of American parents. PG-13 places larger responsibilities on parents for their children''s moviegoing. The voluntary rating system is not a surrogate parent, nor should it be. It cannot, and should not, insert itself in family decisions that only parents can, and should, make. Its purpose is to give prescreening advance informational warnings, so that parents can form their own judgments. PG-13 is designed to make these parental decisions easier for films between PG and R. ', 'Parents Strongly Cautioned. Some material may be inappropriate for children under 13.', 'Parents are urged to be cautious. Some material may be inappropriate for pre-teenagers.');
INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'NC-17', 'No One 17 & Under Admitted', 'This rating declares that the Rating Board believes that this is a film that most parents will consider patently too adult for their youngsters 17 and under. No children will be admitted. NC-17 does not necessarily mean "obscene or pornographic" in the oft-accepted or legal meaning of those words. The Board does not and cannot mark films with those words. These are legal terms and for courts to decide. The reasons for the application of an NC-17 rating can be violence or sex or aberrational behavior or drug abuse or any other elements which, when present, most parents would consider too strong and therefore off-limits for viewing by their children.', 'No One 17 & Under Admitted', 'Clearly adult. Children are not permitted.');
INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'NR', 'NR (Not Rated)', 'This film has not yet been rated by the MPAA.', 'This film has not yet been rated by the MPAA.', 'This film has not yet been rated by the MPAA.');
INSERT INTO `rating_mpaa` (`id`, `name`, `label`, `description`, `description_short`, `short_sweet`) VALUES(NULL, 'R', 'Restricted', 'In the opinion of the Rating Board, this film definitely contains some adult material. Parents are strongly urged to find out more about this film before they allow their children under 17 to accompany them. An R-rated film may include hard language, or tough violence, or nudity within sensual scenes, or drug abuse or other elements, or a combination of some of the above, so that parents are counseled, in advance, to take this advisory rating very seriously. Parents must find out more about an R-rated movie before they allow their teenagers to view it.', 'Restricted, Under 17 Requires Accompanying Parent Or Adult Guardian', 'Contains some adult material. Parents are urged to learn more about the film before taking their young children with them.');
